project_id = "zzwrugobhedcstcpsknz"

[functions.send-push-notification]
verify_jwt = false

[functions.task-recommendations]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.scheduled-notifications]
verify_jwt = false

[functions.validate-task-proof]
verify_jwt = false

[functions.verify-task-proof]
verify_jwt = false

[functions.ai-calendar-schedule]
verify_jwt = false